### ISSUE TITLE
Data layer & business layer mixed together

### ISSUE THREAD

**Issue by FluffyJack** [Prismatik/redbeard#106]
For the stuff that's generated for models right now, most of it is just data layer stuff, e.g dealing with rethink, etc. What the design screams a bit much is put your business logic in with the database code. There is also HTTP logic in the model, tightly coupling the data and delivery layer and therefore everything in between. Thoughts @davidbanham?

**Comment by davidbanham** [comment]
Can you give concrete examples? What http logic is in the models?

Since #91 and #2 it should now be:

routes -> http
controllers -> business logic
models -> database logic & validation

**Comment by FluffyJack** [comment]
HTTP Logic
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L67
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L74
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L77
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L95
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L103
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L113
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L144
https://github.com/Prismatik/redbeard/blob/master/model/model.mustache#L149

Delivery Layer Concern - Data validation before being placed into the actual system, should end at the routing layer or maybe one layer below, not be in the model layer.
https://github.com/Prismatik/redbeard/blob/master/model/lib/model.mustache#L1

No separation of business logic and data storage - controller talks directly to the model continuing the same weird Rails bastardisation of [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller). It actively encourages users of these files and APIs to then mix business logic in with the verbose, though necessary, database code.
https://github.com/Prismatik/redbeard/blob/master/model/controller.mustache#L8

**Comment by FluffyJack** [comment]
My suggestion:

routes -> http
controllers -> orchestration
models -> business logic
database adapter/binding -> database logic & data sanatisation (validation is still business logic, the schemas are just there to make sure data doesn't get messy)

**Comment by davidbanham** [comment]
Right, so we're talking about the httpErrors in the models. I would argue that's not actually http logic, it's just a way to avoid having to define a bunch of error consts and then map from those back to HTTP error codes in the routing layer.

> Delivery Layer Concern - Data normalisation before being placed into the actual system, should end at the routing layer or maybe one layer below, not be in the data layer

Yep, agreed. That function should be pulled up into the routing layer. Good catch.

> It actively encourages users of these files and APIs to then mix business logic in with the verbose, though necessary, database code.

The pattern shouldn't actively encourage that, but I think it should _allow_ it. Forcing people to encode all of their business logic into something that can be expressed in the DSL of your database binding can lead to some horrible inefficiencies. The database's query language is the most powerful way of moving computation closer to the data when that's required. In the case of a complicated join or conditional logic that has to iterate over many pieces of data, I want to do that in the database rather than doing a round trip between each evaluation of the conditional logic.

What I think the current pattern says is "Put your business logic in controllers. Slice and dice the params, add new ones, orchestrate other actions, etc, then hand those over to the model and let it generate a query based on them. If for some reason you _have_ to, you can also pop over to the model and add some code into the query generation pipeline."

If it's communicating something different to you, though, we need to figure out why there's a diff and solve it.

re: your suggestion, could you please expand on the difference as you see it between orchestration and business logic?

**Comment by MadRabbit** [comment]
@FluffyJack i've done some rework in this regard in collaboration with dave. we've settled on the following formula:

```
routes -> req/res
controllers -> business logic
models -> value objects with crud interface and validators
```

i was trying to sway it away from having another CRUD interface on controllers and leave them as pure business logic, but failed :)

either the case, please review the new structure

**Comment by s-taylor** [comment]
Having spoken to Dave I now understand the split between models and controllers and it works well, particularly in enabling an easier upgrade of redbeard in future. I do however still have an issue with the structure of the tests. I feel like combining route / controller / model testing all in one is the wrong approach. The existing test suite is really heavily coupled in that you're always testing all three at once. We definitely should have these type of tests, tests that send http requests and test the server end to end but I think every test being this way doesn't make sense.

In Ordermentum what we did was test everything directly against the resource directly, i.e. the .get, .create, .update, .delete, .watch functions without sending http requests.
The controller's job (or route as it's called in redbeard) is effectively to take the request and pass this through to the underlying resource, then respond with either the success or error case. So then we tested this as well, but only tested a single success and single error case and ensured the response / http status code gets bubbled up accordingly.
I felt this was much neater because as long as you know your success / error responses are being sent to the client correctly, you don't really need to send an http request for every test case.

**Comment by MadRabbit** [comment]
@s-taylor i actually did exactly that in the `thinky` branch. there are controller tests that are more like unit tests, where you can test all the business logic separately from the HTTP stack and create all sorts of edge cases. and then there are `test/routes` which are integration tests that do end-to-end testing

**Comment by s-taylor** [comment]
> @s-taylor i actually did exactly that in the thinky branch. there are controller tests that are more like unit tests, where you can test all the business logic separately from the HTTP stack and create all sorts of edge cases. and then there are test/routes which are integration tests that do end-to-end testing

Love your work @MadRabbit  👍
