### ISSUE TITLE
Automatic route mounting won't support folders & is inflexible

### ISSUE THREAD

**Issue by FluffyJack** [Prismatik/redbeard#107]
**Topic**: https://github.com/Prismatik/redbeard/blob/master/base/index.mustache#L18

If I was to leave the flat structure or deviate from the assumed structure I would need to then rewrite my routes explicitly.

Workaround if using folders is to have for example `routes/admin/index.js` which has an `express.Router` in it, which then requires it's own sub-routes explicitly. This still means a chunk of the `express.Router` API is cut off from use at the top level.

**Proposed solution**

Have a `routes/index.js` file that has new routes appended at the top for when they're required and explicitly added to a list of mounted routes.

e.g.

```
const express = require('express');
const userRoutes = require('./users');
const postRoutes = require('./posts');

module.exports = express.Router()
  .use(userRoutes)
  .use(postRoutes);
```

Then if you generate a comments scaffold:

```
const express = require('express');
const userRoutes = require('./users');
const postRoutes = require('./posts');
const commentRoutes = require('./comments');

module.exports = express.Router()
  .use(userRoutes)
  .use(postRoutes)
  .use(commentRoutes);
```

**Comment by davidbanham** [comment]
What's the benefit of doing it explicitly over implicitly? If the task is just to support nested folders within `/routes` for code organisation it could be more simply done with a recursive directory walk rather than a single layer walk.

**Comment by FluffyJack** [comment]
Namely that it actively discourages the proper use of the `Router` API. When someone does want to break what this convention can handle (and suggesting to make this handle more means adding greater complexity to that function) they would have to rewrite this (breaking the upgrade path we've set out, which is a whole other problem I have) to be explicit. If you have more than just a small handful of files you'll immediately go to one of the easy hacks (ignoring the upgrade path issue).

Two other smaller reasons are generated application frameworks in the JS world are known for their transparency, where newcomers to the framework will not necessarily understand the "Rails Magic" that's going on here, and (very small) that it doesn't match with ES6's requirements of `import` and `export` being at the top level of a module.

To reverse the question, what is the benefit of doing this implicitly over explicitly? Less lines of code? We're talking 2 lines per route, which can be added by the generator anyway. Less code != more clarity or simplicity.

**Comment by davidbanham** [comment]
The primary benefit is that in order to have the generator add explicit route bindings we would need to have two separate processes adding code into the same file. ie:

`redbeard controller foo`

and routes/index.js looks like:

```
const express = require('express');
const fooRoutes = require('./foo');

module.exports = express.Router()
  .use(fooRoutes);
```

And then:

`redbeard controller bar`

And it needs to look like:

```
const express = require('express');
const fooRoutes = require('./foo');
const barRoutes = require('./bar');

module.exports = express.Router()
  .use(fooRoutes)
  .use(barRoutes);
```

Getting from the first state to the second is really not simple, especially when there have been other modifications to the file. I can't envision a reliable way to do it that doesn't involve parsing the AST.

If what we're talking about here is using `Router` rather than directly modifying `app`, would this not suffice?

```
const router = require('express').Router()

fs.readdirSync('./routes').forEach(name => {
  const route = require(`./routes/${name}`);
  router.use(route.http);
});

module.exports = router;
```

(Obviously leaving out the socket.io bits for simplicity of discussion)

I don't think we're at risk of falling prey to Rails Magic, since all the code is right there in front of you. It's plain to see what's happening. `fs.readdirSync` and then a `forEach`. The confusing thing about Rails is the spooky action at a distance that happens when something deep within the bowels of the library decides what files are being loaded and in what order they're being executed. That's not the case here. It's a very node-friendly, very explicit bit of procedural code.

**Comment by davidbanham** [comment]
Since this was filed, we now have `routes/index.js` that exports an array. By default, it slurps all the files in the routes folder and returns them in an array.

If you want, there's nothing stopping you from:

a) Requiring in sub-dirred routes manually and exporting them in a specific order in that array
b) Rewriting both `index.js` and `routes/index.js` to use a totally different structure

We still haven't done anything about exporting a Router rather than the functions. I'm not opposed to that, just not certain how it'll play in with the Socket routes.

**Comment by MadRabbit** [comment]
resolved in the `thinky` branch
