### ISSUE TITLE
Tests take way too long

### ISSUE THREAD

**Issue by sgentle** [Prismatik/redbeard#112]
30 seconds for Shortlyster on my laptop with a bunch of 100-300ms tests. What's that about?

✓ returns 200 ok
✓ return an object with a .result property
✓ accepts search params in the querystring (58ms)
✓ does not match non-property search params in the querystring (50ms)
✓ paginates data when asked **(119ms)**
✓ skips records when asked (84ms)
✓ orders data when asked **(302ms)**
✓ orders data in reverse when asked **(143ms)**
✓ returns n matching docs with a count of all matching docs **(104ms)**
✓ returns n matching docs without a count of all matching docs  **(112ms)**
✓ returns only a count with no matching docs **(107ms)**

I notice something about bcrypt in the test comments. Is there any way we can turn that off? And, architecturally, should we really be doing so many integration tests? Could we mock out rethink so we're not hitting the database all the time? Maybe even mount app's express middleware directly rather than making everything do a roundtrip via HTTP?

**Comment by davidbanham** [comment]
We _could_ mock rethink, but it would be hard and need maintenance.

Mounting directly rather than HTTPing is something on the roadmap as per #53.

We could mock bcrypt pretty easily. Not sure how much speedup it would give us, though.

I think the main area we should be pursuing for test speedup is making the suite run sets in parallel. Your laptop probably had a bunch of cold cores during the run.
