### ISSUE TITLE
Static vs dynamic middleware

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#116]
I added an `error` middleware but needed it to run after all other middlewares, which is a problem because the current `fs` read loop that dynamically plugs in all middlewares found in the `./middleware` folder doesn't have any notion of ordering.

**Solutions/suggestions:**
1. Scrap dynamically reading middlewares - still keeping them snugly in `./middleware` - and instead use them where needed eg. `app.use(middleware)`, in whichever order they might be needed.
2. Could use a some kind of faux ordering system with filenames?  eg. `_middleware` to grok pole position.
3. As above, this could similarly be used to skip middlewares, if those particular middleware needed to be used in a specific way.
4. Use a custom mini DSL for middleware modules which could include ordering information eg.
```
module.exports = {
  order: 1,
  module: () => ...
}
```

I prefer 1. as a solution, as I don't think the benefits of having middleware loaded automatically outweigh the issue I outlined above.  With express/restify, you plug them in at `app.use` and walk away, so I don't think developers would have a problem if this is the case.

Thoughts?

**Comment by davidbanham** [comment]
I actually favour door number 2, followed by door number 4. They're both basically the same thing, except in 1 we're encoding the information in the filename, whereas in 4 we're encoding it in the exported data. I think door number 1 is better as it's clearer. A simple `ls` tells you what you need to know rather than inspecting every file. It does make opening those files in an editor a little grosser, though. You need to remember not only their filename but also their runlevel.

As soon as either of these mechanisms don't work for a user, they're free to just delete the automated file loading code and replace it with an explicit list or any other mechanism of their own devising.

As a principle, I'd rather keep it simple for the 80% than demand that they Do More Work based on the more complex needs of the 20%. The hard exception to that rule, though, is where the solution for the 80% closes a door on the 20% or makes their job unacceptably difficult. At that point, we take on the complexity.

So the user experience becomes:

Name your middlewares with a prepended runlevel if you need a little control over what gets loaded where.
If that ever gets burdensome, just blow away the fs loop and require them in manually.

**Comment by MadRabbit** [comment]
i think this one is resolved in the `thinky` branch. the idea basically is that there is no point in generalizing middleware in loops like you originally did. the order of middleware matters and often middleware only used contextually. hence it should be handwired depending on an application.

as Dave said:

>  just blow away the fs loop and require them in manually.

it's already done
