### ISSUE TITLE
Redbeard CLI consistency

### ISSUE THREAD

**Issue by lyntco** [Prismatik/redbeard#129]
We run `redbeard model dog` but `npm run migration dog` and `npm run migrate`

I think for generating files we should keep it to `readbeard thing x` but running the migration is okay to stay as `npm run thing`

**Comment by davidbanham** [comment]
You couldn't have `npm run thing` as it'd require creating a separate npm script for every kind of `thing`

The reason that the migrations are run as an npm script rather than a redbeard generator is for version control. You always want to run the same migration generator for your project, rather than whatever version the global binary happens to have.

There's a case to be made, by the way, for also moving the `redbeard model` code into an npm script. You'd install redbeard as a local dep of the project at a particular version. That way any time you run redbeard, it's always the same version as the one that generated your project in the first place.

When it comes time to upgrade redbeard, that's an obvious thing with a commit to package.json altering the version string. At the moment it's up to you to add a commit message being all "Using a new version of the generator".
