### ISSUE TITLE
Run with docker

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#156]
I had assumed the project could be run with docker - I guess after just coming off another project where it was working like that - could we add an `npm run docker` start script?  Seems like all our other projects currently have that.  I think it's just `rethinkdb` service that's needed yeah?  Might be overkill, but it would be nice to have some consistency I guess.

`npm start` gives you a garbled message which isn't very helpful - I just forgot to have `rethinkdb` running first, but perhaps that could be something more useful eg.
`Please run rethinkdb blah blah` ?

**Comment by MadRabbit** [comment]
yup totally with you here. one question though. i kind of feel that adding docker related stuff into `package.json` is dodgy. basically `package.json` is supposed to be platform agnostic, it should only have the app specific things. and docker is an infrastructure problem.

so i kind of feel that we're mixing those two concerns and it's not healthy. and i've been contemplating two options basically:

1) `Makefile` - a bit oldschool but relatively widely used by node folks
2) `bin/` folder scripts

both approaches are somewhat unixy, and both are used by node teams. Makefiles seem a bit more standard to me, but they don't let you write javascript in them. `bin/` stubs are highly customizeable and allow you to throw all sorts of stuff in them. although they tend to grow a bit more chaotic at times.

either one of them would do the trick i think. the important bit here is that we should docker related commands set outside of `package.json` to keep the infrastructure concerns away from the pretty code stuff.

so, the question, really: * do you want: *

a) keep making mess in package.json
b) use Makefiles for organizing app related tasks
c) go with a proper `bin/` folder stuff
d) i don't care

please post your opinions in here.

**Comment by davidbanham** [comment]
I'd be happy either way. Package.json was a fine solution when it was just one or two commands but I think the complexity has outgrown it.

Makefiles would be my preferred option because they're language agnostic, but as I said I'd be happy either way.

**Comment by nwinch** [comment]
I think all three have their place and we should be utilising package.json scripts, Makefiles and /bin scripts all in harmony.

I think we need to have a strong team understanding of when a command should be in package.json vs Makefile. Once we're in sync on that, we should be okay to introduce them into our projects confidently.

**Comment by MadRabbit** [comment]
fortunately this is super easy to fix! basically we need to consider that there are two sides to an application. the application (code) environment itself and the runtime (infrastructure) environment.

an application just takes ENV vars and runs its logic. an application assumes that all the code is installed, configurations are in place and depended services are up and running. an application shouldn't care about things outside of its jurisdiction as much as possible. like which computer it runs on, where the database lives, which environment is that, etc. it is just a piece of code.

and then there is the infrastructure side, which cares about vms and containers and linking the network level together. it makes sure that the app can see the database and load balancers can rotate between apps, etc.

those are basically orthogonal concerns and naturally you want your code base to reflect and respect this separation, so that those pieces could grow separately and not be in each other's ways.

in this picture, a good `package.json` file has basically `start` and `test` scripts in it. package.json is the application side dependency, it knows what needs to be installed and what needs to be called in order for the application to start.

docker stuff is the infrastructure concern and it is a good idea to pull it out of the package.json. docker should spawn the infrastructure, connect things together and _then_ call package.json to actually execute the program. if that makes sense.

so i'd put all docker stuff into a separate layer, we have options here. it could be a simple Makefile, or it could be a `bin/start` file. or we could even go further and create a global package called `dpm` which is a docker wrap around `npm`. or something like that.

the main point here is that `package.json` should only have the application specific things in it

**Comment by MadRabbit** [comment]
as the result of discussions about this topic we came up with a task to build a separate docker automation package as a way to standardize the the processes and toolset for the issue https://github.com/Prismatik/redbeard/issues/175
