### ISSUE TITLE
Route paths using filenames as relative base

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#160]
The scaffolded route files in `/src/routes` seem to use the actual filename as the base relative path for each endpoint listed within the file eg. `/src/routes/schema` has a `.get('')` which maps out to `/schema`.

I found it slightly confusing.  When sifting through route files I find it easier just to have the exact route string listed in the file.  Otherwise I'm having to contextual pair the filename to the route I'm looking at when you're switching between files and seeing a lot of `.get('')`.

What is the rationale to do it this way?  It's the first time I've seen it done that way so I'm curious as to the pros and cons.

**Comment by davidbanham** [comment]
It allows you to mount the controller/handler under multiple paths. Very handy for backwards compatibility as routes change.

**Comment by nwinch** [comment]
Hmm I don't quite see the benefit.  Are you able to give me an example scenario to help me understand?

**Comment by davidbanham** [comment]
If you change the name of the Things resource to be called Stuff, you only need to change the way it's mounted, rather than altering every string in the controller.

**Comment by nwinch** [comment]
Hmm how often would that happen?  Maybe once or twice in the beginning of the proejct?  It might not happen at all.  Find/replace would be a much easier solution I think.  It doesn't feel like it's an actual problem that would happen enough that really needs solving with code to me.

It seems a much more known pattern - from what we've done so far with out projects - to have the actual route string listed.

**Comment by davidbanham** [comment]
I'ma tag in The Captain here.

@MadRabbit ^

**Comment by MadRabbit** [comment]
so basically the pattern since express 4 is that you split your routes into a tree where each level mounts branches. and every branch is treated as an independent tree. the idea is that a router branch is conceptualized as a _resource_, a handler of specific type, which then can be mounted somewhere. kind of like that

```js
const { Router } = require('express');
const blogs = require('./blogs');
const comments = require('./comments');

module.exports = new Router()
  .use('/blog', blogs)
  .use('/blog/:id/comments', comments);
```

The idea is that it helps with maintainability because each resource doesn't know about a larger picture. You could move them to other routes, mount to two routes at the same time, like for example when you version your API, etc. The whole application could be included as a dependency and specific resources could be remounted in completely different places.

in a short, it removes coupling between a resource and its application, which allows flexibility in the future and pushes you towards thinking in terms of RESTful resources more.

this might look a bit weird first, but it has a principle under it, and it's fairly simple. you get used to it in no time :)

**Comment by nwinch** [comment]
Ahh right, thanks mate.  I get it now :)  It kinda threw me at first, but now it makes sense.

Thanks also Dave, you explained it more succinctly, I just needed a bit of hand holding :)
