### ISSUE TITLE
/schemas folder location

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#164]
Why do schemas live in `/config/schemas` ?

I think schemas have their own life and purpose and can live on the root level.

**Comment by MadRabbit** [comment]
basically as far as i'm concerned schemas are an application configuration, so they go in `config/`.

the longer version is that i want a consistent projects structure that has specific buckets for everything; and those buckets grow as a tree. at the top level it is basically `code`, `tests` and `configuration`. then within those we specialize `src/module_1`, `src/module_2`, `config/thing_1`, `config/thing_2`.

tree like structures scale much better and more logically than flat structures, it eliminates a whole class of decisions making and navigation issues. going from larger buckets to smaller, more specialized ones is perfectly intuitive.

overall we are heading to a standard project structure that looks somewhat like this:

```
bin/ <- executables
doc/ <- docs
config/ <- configuration management
src/ <- application code
test/ <- tests code
```

with exception of `migrations/`, everything else should fall into those categories, so that other humans will immediately know where what goes regardless to a project's nature

**Comment by davidbanham** [comment]
I agree. Schemas are configuration and that's especially true in the way we use them.

**Comment by nwinch** [comment]
Cool, makes sense, I can roll with that.
