### ISSUE TITLE
Last build time + commit

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#167]
Often the question arises on a project "Hey DevOps person, can you please check that the testing/staging server has udpated?  QA can't see the latest updates".

The problem here is that QA will report something as Failed only because it hasn't updated, which means then that a developer is interrupted to double check the update is there, and then that flows on to chasing DevOps.

One solution is to include a "Last built at 12th July 2016 3:05pm with commit {sha}" in the footer of our apps?  I'm not sure the best place that this would be implemented - in `redbeard` or `redbeard-ui`, or the custom UI for the project, or both etc..

This would give QA an immediate "sense check".  So if a dev says "hey, the thing is ready to be tested now, I'm pretty sure I've fixed it!", and QA tests it, but it fails exactly like before, then there is a strong possibility it may have not updated, and they then have some information at hand to tell them instead of chasing people to check - "Oh, I see testing hasn't updated from 4 hours ago, cool, I can either wait a few more minutes to see if it's still updating, or I'll definitely chase someone to check the build" - instead of failing the ticket again and starting the process over.

Right now I definitely see it saving people time and unnecessary context switching and conversations.

Thoughts?

**Comment by MadRabbit** [comment]
good idea, but i think it shouldn't be in neither. imho this is not the "application" issue, it is the runtime environment issue.

i think the PR apps that will have SHA as the subdomain would be the proper solution to the problem. another, simpler option would be to just ask @one19 to dump a `build/sha.html` file or something as a post build task in CI. so that a person could go to a `/sha` url and see the currently deployed sha.

either one is the case, i think the application itself shouldn't care where and how it's run

**Comment by davidbanham** [comment]
I agree with the rabbit. I'll task Drew on getting it done.

**Comment by davidbanham** [comment]
I've implemented this on the individual projects as part of the devops pipeline.
