### ISSUE TITLE
Sockets for all the things

### ISSUE THREAD

**Issue by s-taylor** [Prismatik/redbeard#60]
Nath and I were discussing yesterday some of the challenges around using the redbeard API and sockets in conjunction. For example when you want to create a record, currently you must use the API endpoint.

What would normally happen if you were just using an API is you'd POST your document and then use the success response to add the document to state. But since we're using sockets the new document should come through automagically without needing to listen to the response. But then if it errors we still need to do something?

An alternative might be to channel all the things through sockets? Is there any reason we can't send create, delete, and update requests via web sockets as well? We could also have web sockets emit error events for when a create, delete or update request fails. That will make things cleaner than working with two interfaces. We could also then allow the `redbeard controller [name]` command to scaffold just the API endpoints, the websocket interface or both. Thoughts?

**Comment by MadRabbit** [comment]
you can do CRUD over a web-socket and it kind of works. that's what meteor does. but sockets is a pain in the neck for non web API consumers. micro-services integration, CLIs, mobile apps. they all would prefer a JSON API. because it is a standard approach and everyone knows how they work.

plus there is no real standards around doing things over a socket. HTTP verbs provide a standard language to talk to a service. in case of a socket you will have to come up with your own home brew format.

plus, doing authentication for a long running connection is a bit of an issue. say someone opened a socket and started doing bad things. how do you revoke their access effective immediately? with JSON API you block the access token, with a web socket you can revoke a token but the connection is already opened and unless you find it and disconnect manually the user will keep doing things

**Comment by davidbanham** [comment]
I agree. I don't think it makes sense for Redbeard to drop HTTP REST in favour of a pure sockets approach. It would be a compatibility nightmare with the rest of the non-RB ecosystem.

There's no technical reason we couldn't support CUD over sockets as well as HTTP, but I don't think it gains us anything.

To your point about control flow in an application, there's nothing _stopping_ you from using the response of the POST to add that document into the local state tree. The joy of the socket interface is that you just don't have to bother. Instead of having to figure out how you insert that new document into the existing collection of documents within the state tree for that specific data structure, you just hook it up to a generic "There was an error! Fix it!" flash message and walk away.

I'm closing this, but it a "Let's not let things carry on indefinitely" close rather than an "There will be no further discussion!" close. Feel free to re-open if there is more to say.
